### ISSUE TITLE
Loser Role

### ISSUE THREAD

**Issue by spacepigoink** [FrostiestBunny/oink-bot#2]
Add a loser role if you purposefully fail extreme punish. 
If user fails extreme punish within the first 30s, assign the loser role to them for the next hour.
Loser role means they can't view any other channel except for general and has a super special loser channel just for them.
Users can grab the Loser Punish role to access the channel and bully the Loser :D

**Comment by FrostiestBunny** [comment]
I shall get right on that, mysterious person.
