### ISSUE TITLE
Add gambling functions

### ISSUE THREAD

**Issue by FoolOfMadness** [FrostiestBunny/oink-bot#6]
blackjack for sure
poker if possible
cointoss
dice rolls
possibly betting oinks if able

**Comment by FoolOfMadness** [comment]
betting oinks has now been separated out onto issue: #27

**Comment by spacepigoink** [comment]
fix the dice to show:

User rolled ten 20-sided dice... instead of "User rolled 10 20-sided dice..."

it's hard to read it nyaNerd

**Comment by FoolOfMadness** [comment]
may nyaGiveUp on poker as it's better as a multiplayer experience which I'm not sure we could provide with a slash command.
it would probably be better as an activity but that's already in Discord as is so this feature could be scrapped
